### ISSUE TITLE
32bit ARMv7 binary

### ISSUE THREAD

**Issue by Haxk20** [electroneumclassic/electroneum-classic#4]
While we can crosscompile for ARMv7 its still not best solution to crosscompile and it would be best to provide those binaries on release too since this would make it possible that i can make arch linux makepkg for ARM without it freezing then entire system trying to compile it on my Rpi2B.

Thanks.

**Comment by Haxk20** [comment]
A little overclock on Rpi helped it to compile without issue but Swap had to be set to 2GB.

**Comment by vans163** [comment]
Crosscompiling I recall is a hard to get working, but would be cool to post a working docker container or script to get it built.
